<?xml version="1.0"?>
<package format="3">
  <name>ble_hardware_bridge</name>
  <version>1.0.0</version>
  <description>Production ROS 2 cmd_vel to BLE GATT hardware bridge.</description>
  <maintainer email="maintainer@example.com">CityWalker</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>pkg-config</build_depend>

  <depend>geometry_msgs</depend>
  <depend>libglib2.0-dev</depend>
  <depend>rclcpp</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-matplotlib</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
